export const Permissions = {
  InventoryRead: "inventory:read",
  InventoryAdjust: "inventory:adjust",
  TasksCreate: "tasks:create",
  TasksRead: "tasks:read",
  TasksUpdate: "tasks:update",
  OrdersRead: "orders:read",
  OrdersCreate: "orders:create",
  TripsRead: "trips:read",
  TripsDispatch: "trips:dispatch",
  VehiclesRead: "vehicles:read",
  VehiclesManage: "vehicles:manage",
  DriversManage: "drivers:manage",
  MobileSyncPull: "mobile:sync:pull",
  MobileSyncPush: "mobile:sync:push",
  MobileUploads: "mobile:uploads",
  MobileGpsBatch: "mobile:gps:batch",
  MobileSos: "mobile:sos",
  BillingRead: "billing:read",
  TenantsManage: "tenants:manage",
  ClientsManage: "clients:manage",
  ClientsRead: "clients:read",
  PlansManage: "plans:manage",
  FeatureFlagsManage: "feature-flags:manage",
  AuditLogsRead: "audit-logs:read",
  SettingsManage: "settings:manage",
  UsersRead: "users:read",
  UsersInvite: "users:invite",
  RolesManage: "roles:manage",
  ApiKeysManage: "api-keys:manage",
  WarehousesManage: "warehouses:manage",
  NotificationsRead: "notifications:read",
  PackStationScan: "pack-station:scan",
  ReturnsRead: "returns:read",
  ReturnsCreate: "returns:create",
  ReturnsApprove: "returns:approve",
  ReturnsInspect: "returns:inspect",
  ReturnsRefund: "returns:refund",
  TenantDashboardRead: "tenant-dashboard:read",
} as const

export type Permission = (typeof Permissions)[keyof typeof Permissions]
