export const Roles = {
  SUPER_ADMIN: "SUPER_ADMIN",
  TENANT_ADMIN: "TENANT_ADMIN",
  WAREHOUSE_MANAGER: "WAREHOUSE_MANAGER",
  WAREHOUSE_STAFF: "WAREHOUSE_STAFF",
  LOGISTICS_MANAGER: "LOGISTICS_MANAGER",
  DRIVER: "DRIVER",
  CUSTOMER_CLIENT: "CUSTOMER_CLIENT",
  TENANT_USER: "TENANT_USER",
} as const

export type Role = (typeof Roles)[keyof typeof Roles]
